Removes template string if $\{ is removed
meganrogge/template-string-converter pull request #19
Opened 2020-10-20 22:20 UTC by xNocken

This is a PR for #16.

It will replace the template strings if you remove ${ from the string. 
It will use the prefered quotes set with "template-string-converter.quoteType".
If nothing is set it will fallback to double.

If you have any feedback just tell me :)

2020-10-20 22:32 UTC, meganrogge commented
Looks good at first glance. I’ll check it out tomorrow and probably merge it.

2020-10-21 15:27 UTC, meganrogge commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
My concern with this conditional is that it won't cover the cases we are interested in.

I understand the request to be: when I've typed ${ within a string and it's been autocorrected by this extension to `${(cursor here now)}` if no text gets added, then it should be reverted to "". So we'd have to monitor the history of where the autocorrect has taken place. And maybe after some time interval if no text gets added, then correct back to quotes. We'd essentially have to monitor if the change is from ${stuff} to ${} within backticks. But then even that would be a mistake to correct back to "" because let's say you delete the stuff object and want to add an info object. Deleting stuff would revert this to "". Is this your understanding also?

Also, let's say  someone forgets they've installed the extension and starts typing `${`, I wouldn't want this to revert to "".

2020-10-21 16:08 UTC, xNocken commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
I don't really understand what you mean. If someone makes a string and adds ${ it should not be reverted to a normal string. It will be changed to a template string. If you accidentally remove it you can just add it and it's a templete string again. And it doesn't remove any content that's in there. It just changes the two chars.

2020-10-21 16:23 UTC, RobiFerentz commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
As the OP of the suggestion, having a history of which strings were changed was not what I had in mind (also, way too much work 😛  ). Essentially, **any** string that does **NOT** have "${" in it should by definition not be a template string, whether it was one before or not. 

Just my 2 cents.

2020-10-21 18:54 UTC, meganrogge commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
@xNocken this is what I'm seeing when I merged your changes locally. as I indicated, typing within backticks isn't possible because it seems to get corrected to quotes before I could even type ${ .

Additionally, the changes break the extension's main purpose, to convert from quotes to backticks. Are you seeing this as well when you test it locally?

I think your idea is cool @RobiFerentz and like that you tried to add it to this extension @xNocken, but think perhaps this would be better suited as its own extension that you could develop with the code you wrote here.
![recording (7)](https://user-images.githubusercontent.com/29464607/96769522-18f92200-1394-11eb-9d64-18e6e639f86d.gif)

2020-10-21 19:23 UTC, xNocken commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
It still works for me. Can you maybe send your settings that i can test it? I only tested with the "template-string-converter.quoteType" settings. And the problem that you cant start with backticks is a true problem but i think it wouldnt be a big problem because you can just use other ones. And i dont think it should be a other extension. It basicaly does the same just backwards. There are linters like eslint that only allow you to use template strings if you use variables in it and force you to use them if you need variables in a string.

2020-10-21 21:22 UTC, meganrogge commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
@xNocken It wasn't your code that was causing it to break - now I've resolved that.

I don't like this behavior because it won't even let me type `${`. Before I can get to the { it has corrected to quotes. As a user of my extension, I find that off-putting and unexpected. For me, the cons outweigh the pros. I'll consider this though if you add it as a setting which is false by default.

2020-10-21 22:25 UTC, xNocken commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
OK I can do that tomorrow

2020-10-21 22:27 UTC, meganrogge commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
Make sure you pull first because of the changes I made today @xNocken

2020-10-22 09:14 UTC, xNocken commented on src/extension.ts
> +          if (withinBackticks(lineText, currentChar) && !lineText.slice(startQuoteIndex + 1, endQuoteIndex).match(/\$\{/)) {
@meganrogge ok I added the setting

2020-10-25 06:18 UTC, xNocken commented
Reminder

2020-10-25 15:14 UTC, meganrogge requested changes
> Reminder

Pls see my comment on line 353

2020-10-25 17:29 UTC, xNocken commented on src/extension.ts
> +    return line.toString().indexOf('`') !== -1 ? line.toString().indexOf('`') : line.toString().indexOf(quoteChar);
I'm a little confused right now. Shouldn't getStartPosition actually have indexOf and getEndPosition lastIndexOf or am I confusing something?

2020-10-25 17:34 UTC, meganrogge commented on src/extension.ts
> +    return line.toString().indexOf('`') !== -1 ? line.toString().indexOf('`') : line.toString().indexOf(quoteChar);
Yes you’re missing the fact that I pass into the getstartquote the substring from the beginning of the string to the current char so in order to get the closest quote to the current position, I have to get the last index of it. And the inverse for get end quote. That way, if there are multiple strings on a line, it’s returning the correct value for the position. @xnocken

2020-10-26 19:07 UTC, xNocken commented on src/extension.ts
> +    return line.toString().indexOf('`') !== -1 ? line.toString().indexOf('`') : line.toString().indexOf(quoteChar);
Ok i checked it and changed it to lastIndexOf @meganrogge

2020-10-27 02:04 UTC, merged

2020-10-27 09:13 UTC, xNocken commented
Can you please add the "hacktoberfest-accepted" label to this pull request?

2020-10-27 13:37 UTC, meganrogge commented
Not seeing that as a label option 

![54FC1CB8-E468-44B9-BA97-8F7C0A348401](https://user-images.githubusercontent.com/29464607/97309196-b38fb000-182f-11eb-824b-1f0e9cf7c879.png)

2020-10-27 17:37 UTC, xNocken commented
You can create it here
https://github.com/meganrogge/template-string-converter/labels